name: tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 8 * * *"
env:
  BASE_URL: ${{ secrets.BASE_URL }}
  NEXT_PUBLIC_WEDDING_DATE: ${{ secrets.NEXT_PUBLIC_WEDDING_DATE }}
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
  AIRTABLE_BASE: ${{ secrets.AIRTABLE_BASE }}
  AIRTABLE_GUEST_TABLE: ${{ secrets.AIRTABLE_GUEST_TABLE }}
  AIRTABLE_GUEST_TABLE_NAME: ${{ secrets.AIRTABLE_GUEST_TABLE_NAME }}
  AIRTABLE_GUEST_TABLE_EMAIL: ${{ secrets.AIRTABLE_GUEST_TABLE_EMAIL }}
  AIRTABLE_GUEST_TABLE_EVENT: ${{ secrets.AIRTABLE_GUEST_TABLE_EVENT }}
  AIRTABLE_GUEST_TABLE_COUNT: ${{ secrets.AIRTABLE_GUEST_TABLE_COUNT }}
  AIRTABLE_GUEST_TABLE_NOTES: ${{ secrets.AIRTABLE_GUEST_TABLE_NOTES }}
  AIRTABLE_GUEST_TABLE_RSVP: ${{ secrets.AIRTABLE_GUEST_TABLE_RSVP }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SENDGRID_TEMPLATE_RSVP_CONFIRMATION: ${{ secrets.SENDGRID_TEMPLATE_RSVP_CONFIRMATION }}
  EMAIL_RSVP: ${{ secrets.EMAIL_RSVP }}
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm i
      - name: Run tsc
        run: npm run typecheck
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm i
      - name: Run lint
        run: npm run lint
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm i
      - name: Run vitest
        run: npm run test:ci
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set timezone to MDT
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Denver"
      - name: Install modules
        run: npm i
      - name: Build
        run: npm run build
      - name: Run cypress
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: "http://localhost:3000"
